[tool.poetry]
name = "fitbase-auto-tests"
version = "0.1.0"
description = ""
authors = ["CinnamonPie <vonahkahs.s.ved@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
